

//---------------ASSESSMENT
export const ASSESSMENT_LOADING = 'ASSESSMENT_LOADING';
export const ASSESSMENT_SUCCESS = 'ASSESSMENT_SUCCESS';
//---------------PROFILE
export const PROFILE_TRAIN_IN_COMPANY_SUCCESS = 'PROFILE_TRAIN_IN_COMPANY_SUCCESS';
export const PROFILE_FAMILY_SUCCESS = 'PROFILE_FAMILY_SUCCESS';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_LOADING = 'PROFILE_LOADING';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const USER_DATA = 'USER_DATA';
