

// ---------STAFF
export const STAFF_SUCCESS = 'STAFF_SUCCESS';
export const STAFF_LOADING = 'STAFF_LOADING';

//-----------LOT
export const LOT_GET_APPROVE_LEAVE_SUCCESS = 'LOT_GET_APPROVE_LEAVE_SUCCESS';
export const LOT_REGISTER_LATE_EARLY_SUCCESS = 'LOT_REGISTER_LATE_EARLY_SUCCESS';
export const LOT_GET_REGISTER_LATE_EARLY_SUCCESS = 'LOT_GET_REGISTER_LATE_EARLY_SUCCESS';
export const LOT_GET_REGISTER_OT_SUCCESS = 'LOT_GET_REGISTER_OT_SUCCESS';
export const LOT_REGISTER_OT_SUCCESS = 'LOT_REGISTER_OT_SUCCESS';
export const LOT_GET_REGISTER_LEAVE_SUCCESS = 'LOT_GET_REGISTER_LEAVE_SUCCESS';
export const LOT_REGISTER_LEAVE_SUCCESS = 'LOT_REGISTER_LEAVE_SUCCESS';
export const LOT_LOADING = 'LOT_LOADING';

//--------------PAYROLL_SUCCESS
export const PAYROLL_LOADING = 'PAYROLL_LOADING';
export const PAYROLL_SUCCESS = 'PAYROLL_SUCCESS';
export const PAYROLL_PERIOD_SUCCESS = 'PAYROLL_PERIOD_SUCCESS';

//---------------APP
export const APP_TYPE_LATE_EARLY_SUCCESS = 'APP_TYPE_LATE_EARLY_SUCCESS';
export const PERIOD_SUCCESS = 'PERIOD_SUCCESS';
export const APP_TYPE_OT_SUCCESS = 'APP_TYPE_OT_SUCCESS';
export const APP_TYPE_LEAVE_SUCCESS = 'APP_TYPE_LEAVE_SUCCESS';

//---------------TIMESHEET
export const TIMESHEET_PERIOD_SUCCESS = 'TIMESHEET_PERIOD_SUCCESS';
export const TIMESHEET_LOADING = 'TIMESHEET_LOADING';
export const TIMESHEET_SUCCESS = 'TIMESHEET_SUCCESS';

//---------------ASSESSMENT
export const ASSESSMENT_LOADING = 'ASSESSMENT_LOADING';
export const ASSESSMENT_SUCCESS = 'ASSESSMENT_SUCCESS';

//---------------PROFILE
export const PROFILE_TRAIN_IN_COMPANY_SUCCESS = 'PROFILE_TRAIN_IN_COMPANY_SUCCESS';
export const PROFILE_FAMILY_SUCCESS = 'PROFILE_FAMILY_SUCCESS';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_LOADING = 'PROFILE_LOADING';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const USER_DATA = 'USER_DATA';
